# vim:tw=0:ts=2:sw=2:noet:ft=make
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/doblabs/click-hotoffthehamster#🪝
# License: BSD-3-Clause

MAKE_LINT_SKIP_PYDOCSTYLE ?= true

